# Generated by Django 6.1.1 on 2026-10-02 21:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("position", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["series", "position"],
            },
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series",
                        to="comics.comic",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "series",
                "ordering": ["comic", "position"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("alt_text", models.TextField(blank=True, default="")),
                ("transcript", models.TextField(blank=True, default="")),
                ("author_commentary", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("unlisted", "Unlisted"),
                            ("followers_only", "Followers only"),
                            ("members", "Members"),
                            ("tier", "Tier"),
                        ],
                        default="public",
                        max_length=16,
                    ),
                ),
                (
                    "federation",
                    models.CharField(
                        choices=[
                            ("federated", "Federated"),
                            ("local_only", "Local only"),
                        ],
                        default="federated",
                        max_length=16,
                    ),
                ),
                (
                    "content_warning",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("sensitive", models.BooleanField(default=False)),
                ("ap_id", models.URLField(blank=True, default="")),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pages",
                        to="comics.chapter",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="comics.series",
                    ),
                ),
            ],
            options={
                "ordering": ["series", "position"],
            },
        ),
        migrations.AddField(
            model_name="chapter",
            name="series",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="comics.series",
            ),
        ),
        migrations.AddConstraint(
            model_name="series",
            constraint=models.UniqueConstraint(
                fields=("comic", "slug"), name="unique_series_slug_per_comic"
            ),
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(
                fields=("series", "position"), name="unique_page_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="chapter",
            constraint=models.UniqueConstraint(
                fields=("series", "position"), name="unique_chapter_position"
            ),
        ),
    ]
