# Generated by Django 6.1.1 on 2026-10-05 06:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comics", "0002_page_scheduled_by_page_page_due_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="alt_text",
        ),
    ]
