# Generated by Django 6.1.1 on 2026-10-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comics", "0002_chapter_series_page_chapter_series_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comic",
            options={"ordering": ["title", "id"]},
        ),
        migrations.AlterModelOptions(
            name="page",
            options={"ordering": ["series", "position", "id"]},
        ),
        migrations.AlterModelOptions(
            name="series",
            options={
                "ordering": ["comic", "position", "id"],
                "verbose_name_plural": "series",
            },
        ),
        migrations.AddConstraint(
            model_name="series",
            constraint=models.UniqueConstraint(
                fields=("comic", "position"), name="unique_series_position"
            ),
        ),
    ]
