# Generated by Django 6.1.1 on 2026-10-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comics", "0003_remove_page_alt_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="comic",
            name="require_reply_approval",
            field=models.BooleanField(default=False),
        ),
    ]
