# Generated by Django 6.1.1 on 2026-10-02 20:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actors", "0001_initial"),
        ("federation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ap_id", models.URLField(unique=True)),
                ("type", models.CharField(max_length=64)),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        default="inbound",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processed", "Processed"),
                            ("rejected", "Rejected"),
                        ],
                        default="received",
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="actors.actor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "activities",
                "indexes": [
                    models.Index(
                        fields=["actor", "direction", "status"],
                        name="federation__actor_i_081882_idx",
                    )
                ],
            },
        ),
    ]
