# Generated by Django 6.1.1 on 2026-10-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("federation", "0002_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="error",
            field=models.TextField(blank=True, default=""),
        ),
    ]
