# Generated by Django 6.1.1 on 2026-10-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="follow",
            name="activity_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
