# Generated by Django 6.1.1 on 2026-10-08 23:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actors", "0001_initial"),
        ("comics", "0004_comic_require_reply_approval"),
        ("social", "0004_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="boost",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boosts",
                to="social.comment",
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="social.comment",
            ),
        ),
        migrations.CreateModel(
            name="CommentBan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_bans",
                        to="actors.actor",
                    ),
                ),
                (
                    "comic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_bans",
                        to="comics.comic",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("comic", "actor"), name="unique_comment_ban"
                    )
                ],
            },
        ),
    ]
