# Generated by Django 6.1.1 on 2026-10-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0005_boost_comment_like_comment_commentban"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="hidden_by_ban",
            field=models.BooleanField(default=False),
        ),
    ]
