# Generated by Django 6.1.1 on 2026-09-26 23:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Instance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=255, unique=True)),
                (
                    "software_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "software_version",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("shared_inbox", models.URLField(blank=True, default="")),
                ("blocked", models.BooleanField(default=False)),
                ("silenced", models.BooleanField(default=False)),
                ("allowlisted", models.BooleanField(default=False)),
                ("reject_media", models.BooleanField(default=False)),
                ("reject_reports", models.BooleanField(default=False)),
                ("last_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ap_id", models.URLField(unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Person", "Person"),
                            ("Service", "Service"),
                            ("Group", "Group"),
                            ("Organization", "Organization"),
                        ],
                        default="Person",
                        max_length=32,
                    ),
                ),
                ("handle", models.CharField(max_length=255)),
                ("domain", models.CharField(blank=True, default="", max_length=255)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("summary", models.TextField(blank=True, default="")),
                ("inbox", models.URLField(blank=True, default="")),
                ("shared_inbox", models.URLField(blank=True, default="")),
                ("outbox", models.URLField(blank=True, default="")),
                ("followers", models.URLField(blank=True, default="")),
                ("following", models.URLField(blank=True, default="")),
                ("featured", models.URLField(blank=True, default="")),
                ("public_key_pem", models.TextField(blank=True, default="")),
                (
                    "ed25519_public_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("private_key_pem", models.BinaryField(blank=True, default=b"")),
                ("ed25519_private_key", models.BinaryField(blank=True, default=b"")),
                ("manually_approves_followers", models.BooleanField(default=False)),
                ("indexable", models.BooleanField(default=True)),
                ("discoverable", models.BooleanField(default=True)),
                ("is_instance_actor", models.BooleanField(default=False)),
                ("last_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("handle", "domain"),
                        name="unique_actor_handle_per_domain",
                    )
                ],
            },
        ),
    ]
