# Generated by Django 6.1.1 on 2026-10-05 06:24

import django.db.models.deletion
import media.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("comics", "0002_page_scheduled_by_page_page_due_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("alt_text", models.TextField(blank=True, default="")),
                (
                    "original",
                    models.FileField(upload_to=media.models._original_upload_to),
                ),
                ("content_type", models.CharField(max_length=64)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("bytes", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="comics.page",
                    ),
                ),
            ],
            options={
                "ordering": ["page", "position", "id"],
            },
        ),
        migrations.CreateModel(
            name="MediaDerivative",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("thumbnail", "Thumbnail"),
                            ("display", "Display"),
                            ("federation", "Federation"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=media.models._derivative_upload_to),
                ),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("bytes", models.PositiveBigIntegerField()),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derivatives",
                        to="media.media",
                    ),
                ),
            ],
            options={
                "ordering": ["media", "kind"],
            },
        ),
        migrations.AddConstraint(
            model_name="media",
            constraint=models.UniqueConstraint(
                fields=("page", "position"), name="unique_media_position_per_page"
            ),
        ),
        migrations.AddConstraint(
            model_name="mediaderivative",
            constraint=models.UniqueConstraint(
                fields=("media", "kind"), name="unique_derivative_kind_per_media"
            ),
        ),
    ]
